### PR TITLE
fix bug in select for single string antenna_name, flatten higher-dimensional arrays in select

### PR DESCRIPTION
**Pull request by bhazelton**
Fixes a bug where if a single antenna_name string was passed it treated the characters in the string as separate antenna names rather than using the whole string as the antenna name.

Also add asserts to prevent problems with nested lists selects.

### CODE REVIEW

**Comment by adampbeardsley** [comment]
I think asserting that ndim=1 is fine. Are there any use cases where people would supply larger dim arrays and we should just flatten?

**Comment by adampbeardsley** [comment]
@bhazelton I went ahead and approved this, but I'll leave it to you to merge pending what you think about my above comment.

**Comment by adampbeardsley** [comment]
Yeah, I'm struggling to think of either a case where flattening is wrong, or an actual use case where higher dim arrays would be input. Either way, we should probably make the assertion error more clear. I think as is it just gives:
`AssertionError:`

**Comment by bhazelton** [comment]
Ok, maybe I'll just change it to flatten the arrays. Then I think I don't need the assert.

**Comment by bhazelton** [comment]
Does the flatten ordering matter?

**Comment by bhazelton** [comment]
@adampbeardsley I changed all the asserts to flattens. Can you take another look when you get a chance?

**Pull request merged**
