### PR TITLE
added pyuvdata_inspect.py script

### PR DESCRIPTION
**Pull request by nkern**
*apologies if this capability already exists. if it does please point me in the right direction!

Tired of having to open a python interpreter, import a `pyuvdata` object, instantiate it and read in a file just to figure out what `Ntimes` is (or related attribute)? Now you hopefully don't have to! With the `pyuvdata_inspect.py` command line tool, you can just do

`pyuvdata_inspect.py --attr=Ntimes zen.xx.HH.uvcA`

and the `Ntimes` of the file is printed to stdout. You can also do other things like

`pyuvdata_inspect.py --attr=Ntimes,data_array.shape zen.xx.HH.uvcA`

to get `Ntimes` and the shape of the `data_array` object etc.

Hopefully this speeds up peoples' workflow to some degree...

### CODE REVIEW

**Comment by pkgw** [comment]
You should rebase this branch onto the current `master` to pick up the fixes to the Travis CI configuration that make testing work again.

**Comment by bhazelton** [comment]
This is nice new functionality, but no one will know about it unless it gets into the Docs! Please at least add some examples to the tutorial,

**Comment by bhazelton** [comment]
@nkern I approved this, but it looks like it has conflicts with master, can you rebase it on master?

**Comment by bhazelton** [comment]
@nkern This PR is still in conflict with the master branch and so cannot be merged. Please *rebase* (not merge) this branch on the master branch. If you need help resolving the conflict or performing the rebase, I'd be happy to help.

**Comment by nkern** [comment]
@bhazelton I think that did it? let me know if there is anything else or if I didn't quite get it right.. thanks

**Comment by nkern** [comment]
@bhazelton i think i'm going to erase this branch, recommit and make a new PR...

**Pull request closed without merging**
