### PR TITLE
pep8 fixes

### PR DESCRIPTION
**Pull request by bhazelton**
@nkern There's still a bare except in your pyuvdata_inspect script, line 62 that I wasn't sure how to fix. Can you fix it and push it to this branch?

### CODE REVIEW

**Comment by nkern** [comment]
@bhazelton its kinda important for the try: except: statement to be there, so I just made a trivial change to make the except hold something, instead of a pass statement. let me know if you were looking for a different kind of fix.

**Comment by bhazelton** [comment]
@nkern I'm sorry, what I wanted you to fix was that the except is bare -- it doesn't specify which error types it is supposed to handle (https://docs.python.org/2/howto/doanddont.html#except). I have no problem with the pass.

**Comment by nkern** [comment]
@bhazelton ah I see. the `except` is bare because each of the `uvd.read_{}` functions raise different kinds of exceptions... so to catch them all I just used a blanket `except` statement

**Comment by bhazelton** [comment]
@nkern You can list multiple exception types in the except statement, it's fine to handle many different ones, but leaving it bare allows it to match exception types you don't expect, as explained in the link I posted. That's why the pep8 standard opposes bare excepts.

I can add in the exception types myself, but I was just looking at the code a bit to figure out what they are, and I am confused by ob_names having 'UVFITS' -- I think it should just have UVData, UVBeam and UVCal, am I missing something?

**Comment by nkern** [comment]
@bhazelton yeah UVFITS can be excluded. ok i updated the except with all of the exceptions the three objects raised when trying to read the wrong files. let me know if you need anything else!

**Comment by bhazelton** [comment]
@nkern Perfect! Thank you!!

**Comment by bhazelton** [comment]
@adampbeardsley can you take a look at this one too? It's just pep8 fixes.

**Pull request merged**
