### PR TITLE
Get ready for Python 3 compatibility

### PR DESCRIPTION
**Pull request by pkgw**
This PR makes a lot of the changes that will be needed to obtain simultaneous compatibility with both Python 2 and Python 3.

It doesn't make all of them. Instead, I've just done enough work to get the test suite passing on Python 2. The addition of all of the `__future__` imports may trigger unexpected problems when running in a pure Python 2 context, but this chunk of work can, in principle, be merged and shaken down before worrying about getting Python 3 to work for real.

### CODE REVIEW

**Comment by pkgw** [comment]
Thanks @plaplant.

**Comment by bhazelton** [comment]
This branch needs to be rebased. @pkgw I'm happy to do it if you want.

**Comment by bhazelton** [comment]
I'm going to rebase this branch. Anyone who has a local copy should delete it and check it back out after my rebase.

**Comment by pkgw** [comment]
Oops, forgot about the need for a rebase, thanks for doing this @bhazelton!

**Pull request merged**
