### PR TITLE
Add pep8 checking to Travis

### PR DESCRIPTION
**Pull request by bhazelton**
To prevent pep8 problems from being missed in PRs.

This ignores the line-length check (code E501).

### CODE REVIEW

**Comment by bhazelton** [comment]
@adampbeardsley @dannyjacobs @jpober I'm of two minds about whether to push for this PR to be merged or not. Partly I wanted to figure out if I could do it and I had just spent some time cleaning up some stuff that had been merged in previous PRs. What do you all think?

**Comment by jpober** [comment]
I don't have a strong opinion.  We've decided the code should be pep8 compliant, but maybe it shouldn't come at the expense of an increased bar for participation in the project.  That said, it's not that onerous to get right either.

**Comment by dannyjacobs** [comment]
But how does it actually work? Does the Travis build just fail if all lights are not green? Or is there a service like Coveralls that tracks our pep8-edness?

**Comment by bhazelton** [comment]
Travis fails on any pep8 miss, but if you look at the Travis log it lists all the problematic line numbers. The fact that this PR is passing Travis means we don't have any problems currently.

**Comment by adampbeardsley** [comment]
I can also go either way. Definitely useful, and maybe we need a little extra push to get people to stay compliant. Typically @bhazelton is the hero that goes through and fixes things, so if this makes her life easier, I think we should implement it.

**Comment by bhazelton** [comment]
Ok, I'm going to merge it. If we find it annoying we can always take it out.

**Pull request merged**
